### ISSUE TITLE
Crypto Tools Telegram Channel

### ISSUE THREAD

**Issue by armcbride12** [hargate/Crypto_Tools#1]
Comments seem to be disabled in your channel.

**Comment by hargate** [comment]
@armcbride12 

Thank you for the heads-up! 

Apparently, a Telegram Channel is only for announcements and a Telegram Group / Super Group is for discussions. I have created a Super Group for feedback and other discussion.

https://t.me/joinchat/IGFPExKP47R6pWmQRr9hiA
